course_name = "自动控制理论B"
repo_type = "normal"
course_code = "AUTO3001B"

description = """
自动控制理论 A 主要学习控制系统的分析（给控制系统分析性能），而自动控制理论 B 主要学习控制系统的综合（给性能指标设计控制器）。
"""

[[lecturers]]
name = "吴爱国"

[[lecturers.reviews]]
content = """
授课认真，讲解细致，按步骤演算各校正过程，生怕学生听不懂。上课给人的感觉是信手拈来 ~~（不知道成语用对了没有。不过他讲的这部分确实也不算难）~~。
频率校正部分的思路较为新颖，值得一听。

自编讲义并印发给学生（每班 2 本），不过其中有较多错误，课件中修正了一小部分；课件中的图片大多是矢量图，非常清晰美观。

仅看课件不一定看得懂（有些页面只有一张图），需要结合听课来理解。

注:2025 年没有发放纸质讲义。
"""
author = [
  { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-06" },
  { name = "Maxwell Jay", link = "https://www.github.com/MaxwellJay256", date = "2025-08" },
]

[[lecturers]]
name = "许鋆"

[[lecturers.reviews]]
content = """
课件来源比较多，主要参考吴爱国老师的讲义。对于讲义上的错误和含糊之处，做了很仔细的修订。讲解较为清晰。板书美观但是比较小，想看清的话建议坐前排。
考勤遵照吴老师意见，2023 年春季有较高强度考勤，2024 年春季则没有。
"""
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-11" }


[[sections]]
title = "学习建议"

[[sections.items]]
content = """
自动化控制理论A 主要学习控制系统的分析（给控制系统分析性能），而自动控制理论B 主要学习控制系统的综合（给性能指标设计控制器）。

自控B 的特点有 4 个：

1. 结果不唯一
2. 存在近似处理
3. 使用经验公式
4. 设计过程具有主观性

频域校正、离散校正、能控能观分解、状态空间综合、非线性系统描述函数法，这些都有非常标准的公式和流程，多做几道题就能掌握，尤其是作业题很有代表性。
"""
author = { name = "Maxwell Jay", link = "https://www.github.com/MaxwellJay256", date = "2025-08" }


[[sections]]
title = "关于考试"

[[sections.items]]
content = """
- 考试难度：中等
- 说明：（20、21 级情况）考试时间可能会比较紧，注意平时练习熟练度。考试题型较为传统，也不会考的较深较难，不用全面复习。注意听老师上课说的「不会考试」的点。

- 2025 年考得很简单，没有任何花样。因此高分段人数也很密集，97 分排名 16 / 130。
- 老师说不考的内容真的不考
"""
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-06" }

[[sections]]
title = "关于实验"

[[sections.items]]
content = "实验占比约 8%（README 未提供更多细节）。"
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-06" }


[[sections]]
title = "学习建议"

[[sections.items]]
content = """
- 自动化专业看家本领，重要性不言而喻。不过其实内容只是稍显繁琐，并不复杂。
- 想读研的同学，可以在学状态空间有关知识的时候，注意打好线性代数基础，涉猎一些《线性系统理论》方面的知识。频域法的部分可能对于考研的同学更为有用。
"""
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-11" }
